Group dependabot created updates for some packages in fewer PRs
FreeTubeApp/videojs-vtt-thumbnails pull request #216
Opened 2023-09-05 06:20 UTC by PikachuEXE

Similar to https://github.com/FreeTubeApp/FreeTube/pull/3968

2023-09-05 11:14 UTC, ChunkyProgrammer approved these changes

2023-09-06 05:44 UTC, efb4f5ff-1298-471a-8973-3d47447115dc submitted a review, later dismissed

2023-09-07 13:30 UTC, ChunkyProgrammer requested changes

2023-09-07 13:30 UTC, ChunkyProgrammer commented on .github/dependabot.yml
> +    groups:
Should groups be moved under the `npm` config instead of github actions?

2023-09-08 00:02 UTC, PikachuEXE commented
Yup fixed

2023-09-08 00:21 UTC, efb4f5ff-1298-471a-8973-3d47447115dc approved these changes
LGTM :)

2023-09-08 18:24 UTC, ChunkyProgrammer approved these changes

2023-09-08 19:11 UTC, absidue approved these changes

2023-09-08 19:11 UTC, merged