Improve linting
FreeTubeApp/videojs-vtt-thumbnails pull request #81
Opened 2023-01-23 19:51 UTC by ChunkyProgrammer

- Improves linting by copying the lint configuration from the videojs-http module
- Improves accessibility of the css
- Updates banner to reference FreeTube instead of the previous package owner
- Some small performance improvements (mainly from linting)

I was thinking of adding stylelint too but the css file is so small and will likely not be changed for a while that I decided against it

2023-01-24 00:24 UTC, PikachuEXE requested changes

2023-01-24 00:24 UTC, PikachuEXE commented on .eslintrc.cjs
> +  }]
strange indent
```suggestion
    }]
```

2023-01-24 03:37 UTC, PikachuEXE approved these changes, later dismissed

2023-01-25 21:47 UTC, absidue commented on .eslintrc.cjs
> +    node: true
Considering that this only going to be used in web environments, do we need to lint for the commonjs and node environments?

2023-01-28 16:21 UTC, absidue approved these changes

2023-01-29 01:14 UTC, PikachuEXE approved these changes

2023-01-29 21:07 UTC, efb4f5ff-1298-471a-8973-3d47447115dc approved these changes

2023-01-29 21:07 UTC, merged